default: &default
  adapter: :mysql2
  encoding: utf8mb4
  charset: utf8mb4
  charset: utf8mb4_bin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: booking_hotel_api_development

test:
  <<: *default
  database: booking_hotel_api_test

production:
  <<: *default
  database: booking_hotel_api_production
